### PR TITLE
Updated unit testing for text extraction functions

### PR DESCRIPTION
**Pull request by DiSuVe**

### CODE REVIEW

**Review by milekpl — CHANGES_REQUESTED** [review]
Why not simply use docx2txt or python-docx-text? Both are open source and we do not need any deep manipulation of Word files here. They are usually pretty basic, and all formatting is gone anyway when going to a corpus management system? Please tell me what is missing in these libraries? Or maybe you haven't found them?

**Comment by DiSuVe** [comment]
> Why not simply use docx2txt or python-docx-text? Both are open source and we do not need any deep manipulation of Word files here. They are usually pretty basic, and all formatting is gone anyway when going to a corpus management system? Please tell me what is missing in these libraries? Or maybe you haven't found them?

I tried using both of those libraries at some point, but none of them support .doc files directly. I also attempted to convert the .doc files into .docx files before extracting text, but it didn't work as intended either.

**Comment by milekpl** [comment]
Ah, now I get it. I'll see what other options we might have.

wt., 9 lip 2024, 16:10 użytkownik DiSuVe ***@***.***> napisał:

**Comment by milekpl** [comment]
Oh, I remember I had to use Apache Tika instead. I have to see whether the
crawler leaves anything unprocessed, as I got zillions of duplicates when I
indexed it with Lucene.

wt., 9 lip 2024, 19:21 użytkownik Marcin Miłkowski ***@***.***> napisał:

**Comment by milekpl** [comment]
OK. I had a closer look on Tika and on our corpus. In fact, we have almost 294 thousand (!) files to convert. Doing this using Python seems like a bad idea (parsing docs is computationally intensive). However, we can add basic metadata to all text files by traversing the directory. This should be relatively easy. Thus, please refactor your code to do just that: assume that there are .txt files, and that they should have associated .json files (unless they are supplement files) so that we could add appropriate metadata. Just ignore all other file formats (I think html can be safely discarded as well).

**Pull request closed without merging**
